Review 3
ademwork/cpp-peer-review pull request #5
Opened 2023-10-18 19:42 UTC by ademwork

2023-10-26 14:28 UTC, c3leron366 requested changes
Пока один файл :(

2023-10-26 14:28 UTC, c3leron366 commented on peer_review/LoadPerson.cpp
> +std::vector<Person> LoadPerson(const DBQuery &query)
Множественное число подходит лучше - т.к. возвращается коллекция. В таком случае будет перегрузка функции LoadPersons с другим набором аргументов

2023-10-26 14:28 UTC, c3leron366 commented on peer_review/LoadPerson.cpp
> +    if (db_allow_exceptions == false)
Этого флага  нет в области видимости

2023-10-26 14:28 UTC, c3leron366 commented on peer_review/LoadPerson.cpp
> +std::vector<Person> LoadPersons(ParamConnectDB param_connect, int min_age, ParamQuery param_query)
аргумент  min_age  не используется

2023-10-26 15:09 UTC, c3leron366 requested changes

2023-10-26 15:09 UTC, c3leron366 commented on peer_review/CheckDateTimeValidity.cpp
> +    void checkHighBound(Tp param, int low_bound, const std::string& msg)
Нейминг, думаю нужен high_bound  и вопрос такой - если Tp это какой-нибудь enum class month,  сравнение с интом не будет работать

2023-10-26 15:09 UTC, c3leron366 commented on peer_review/CheckDateTimeValidity.cpp
> +    CheckDate(DateRestrictions min_rest, DateRestrictions max_rest) : min_rest_(min_rest), max_rest_(max_rest)
объект большой, лучше передавать по константной ссылке

2023-10-26 15:09 UTC, c3leron366 commented on peer_review/LoadPerson.cpp
> +    std::string_view db_name;
тут можно поймать ошибку, если время жизни строки по которой создан db_name закончится раньше, чем используется этот объект

2023-10-26 15:09 UTC, c3leron366 commented on peer_review/CheckDateTimeValidity.cpp
> +    void CheckDateTimeValidity(const DateTime& dt)
Не хватает функции CheckDateTimeValidity, в которой будет конструироваться объект класса и вызываться этот метод

2023-10-26 16:56 UTC, ademwork commented on peer_review/LoadPerson.cpp
> +std::vector<Person> LoadPerson(const DBQuery &query)
Переименовал в ReadPersonsFromDB , так  как у них разный функционал , одна соединяется базой и вызывает загрузку данный, вторая загружает данные из базы

2023-10-26 16:57 UTC, ademwork commented on peer_review/LoadPerson.cpp
> +    if (db_allow_exceptions == false)
Исправил

2023-10-26 16:57 UTC, ademwork commented on peer_review/LoadPerson.cpp
> +std::vector<Person> LoadPersons(ParamConnectDB param_connect, int min_age, ParamQuery param_query)
Исправил.

2023-10-26 17:03 UTC, ademwork commented on peer_review/LoadPerson.cpp
> +    std::string_view db_name;
Это переменная приходит извне, не ясно как её проверить на актуальность.

2023-10-26 17:09 UTC, ademwork commented on peer_review/CheckDateTimeValidity.cpp
> +    void checkHighBound(Tp param, int low_bound, const std::string& msg)
Все таки это название функции, поэтому переименовал CheckHighBound и CheckLowBound.

2023-10-26 17:18 UTC, ademwork commented on peer_review/CheckDateTimeValidity.cpp
> +    CheckDate(DateRestrictions min_rest, DateRestrictions max_rest) : min_rest_(min_rest), max_rest_(max_rest)
Исправил.

2023-10-26 17:27 UTC, ademwork commented on peer_review/CheckDateTimeValidity.cpp
> +    void CheckDateTimeValidity(const DateTime& dt)
Исправил.

2023-10-27 00:39 UTC, c3leron366 requested changes

2023-10-27 00:39 UTC, c3leron366 commented on peer_review/task_3.cpp
можно удалить файл

2023-10-27 00:39 UTC, c3leron366 commented on peer_review/ParseCitySubjson.cpp
> +    ParamCountry(Country& param) : name(param.country.name), iso_code(param.iso_code), phone_code(param.phone_code) , time_zone(param.phone_code), languages(param.languages)
time_zone инициализируется кодом телефонным

2023-10-27 08:03 UTC, c3leron366 requested changes

2023-10-27 08:03 UTC, c3leron366 commented on peer_review/LoadPerson.cpp
> +    std::string_view db_name;
никак, но можно создать строку, которая будет валидна

2023-10-27 08:03 UTC, c3leron366 commented on peer_review/LoadPerson.cpp
> +    if (param_connect.db_allow_exceptions == false)
Это нужно убрать. При попытке использовать конструктор хэндлера бд без исключений, функция не будет работать

2023-10-27 14:19 UTC, c3leron366 requested changes

2023-10-27 14:19 UTC, c3leron366 commented on peer_review/LoadPerson.cpp
> +    std::string_view db_name;
еще можно добавить комментарий к методу установки db_name

2023-10-27 16:07 UTC, ademwork commented on peer_review/ParseCitySubjson.cpp
> +    ParamCountry(Country& param) : name(param.country.name), iso_code(param.iso_code), phone_code(param.phone_code) , time_zone(param.phone_code), languages(param.languages)
Исправил.

2023-10-27 16:07 UTC, ademwork commented on peer_review/task_3.cpp
Удалил.

2023-10-27 16:08 UTC, ademwork commented on peer_review/LoadPerson.cpp
> +    if (param_connect.db_allow_exceptions == false)
Исправил.

2023-10-27 16:33 UTC, c3leron366 approved these changes
Больше вопросов нет

2023-10-27 18:23 UTC, merged